apiVersion: v1
kind: Service
metadata:
  labels:
    app: shared-lock
    coredns-agent-auto: enabled
    coredns-agent-ttl: "30"
  name: shared-lock
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8191
      protocol: TCP
      targetPort: 8191
  selector:
    app: shared-lock
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shared-lock
    app.kubernetes.io/instance: shared-lock
    app.kubernetes.io/name: shared-lock
  name: shared-lock
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: shared-lock
      app.kubernetes.io/name: shared-lock
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shared-lock
        app.kubernetes.io/instance: shared-lock
        app.kubernetes.io/name: shared-lock
    spec:
      containers:
      - name: shared-lock-api
        image: 1010s/shared-lock:main
        imagePullPolicy: Always
        command:
        - /usr/bin/shared-lock
        args:
        - serve
        env:
          - name: SHARED_LOCK_SERVER_PORT
            value: "8191"
          - name: "SHARED_LOCK_ETCD_ADDR_LIST"
            value: "https://etcd.etcd.svc.cluster.local:2379"
          - name: SHARED_LOCK_ETCD_TLS
            value: "true"
          - name: SHARED_LOCK_CA_CERT_PATH
            value: "/cert/tls/ca.crt"
          - name: SHARED_LOCK_CLIENT_CERT_PATH
            value: "/cert/tls/tls.crt"
          - name: SHARED_LOCK_CLIENT_KEY_PATH
            value: "/cert/tls/tls.key"
        ports:
        - containerPort: 8191
          name: http
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8191
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8191
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - mountPath: /cert/tls/
          name: etcd-main-tls
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: etcd-main-tls
        secret:
          defaultMode: 420
          secretName: etcd-main-tls
