name: Docker Build & Push

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/||; s|refs/tags/||')
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          TAGS="${{ secrets.DOCKERHUB_USERNAME }}/my-app:$BRANCH_NAME,${{ secrets.DOCKERHUB_USERNAME }}/my-app:$SHORT_SHA"
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAGS="$TAGS,${{ secrets.DOCKERHUB_USERNAME }}/my-app:$BRANCH_NAME"
          fi
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: deployment/Dockerfile
          push: true
          tags: ${{ env.TAGS }}
